name:                genvalidity-dependent-map
version:             0.1.0.0
github:              "githubuser/genvalidity-dependent-map"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/genvalidity-dependent-map#readme>


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - dependent-map
  - dependent-sum
  - QuickCheck
  - genvalidity

executables:
  genvalidity-dependent-map-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - genvalidity-dependent-map

tests:
  genvalidity-dependent-map-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - genvalidity-dependent-map
